<a href="https://colab.research.google.com/github/Long-Live-Lord-Voldemort/Long-Live-Lord-Voldemort/blob/main/MultipleLinearRegression_SKLearn_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('housing.csv')
df.head()

0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00
0   0.02731   0.00   7.070  0  0.4690  6.4210  78...                                              
1   0.02729   0.00   7.070  0  0.4690  7.1850  61...                                              
2   0.03237   0.00   2.180  0  0.4580  6.9980  45...                                              
3   0.06905   0.00   2.180  0  0.4580  7.1470  54...                                              
4   0.02985   0.00   2.180  0  0.4580  6.4300  58...

In [6]:
df.tail()

0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00
500   0.06263   0.00  11.930  0  0.5730  6.5930  69...                                              
501   0.04527   0.00  11.930  0  0.5730  6.1200  76...                                              
502   0.06076   0.00  11.930  0  0.5730  6.9760  91...                                              
503   0.10959   0.00  11.930  0  0.5730  6.7940  89...                                              
504   0.04741   0.00  11.930  0  0.5730  6.0300  80...

In [7]:
from sklearn import datasets

In [8]:
boston = datasets.load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [9]:
x = boston.data
y = boston.target

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

In [12]:
from sklearn import linear_model

In [13]:
model = linear_model.LinearRegression()

In [14]:
model.fit(x_train, y_train)

LinearRegression()

In [15]:
y_pred = model.predict(x_test)

In [16]:
y_pred

array([32.3914647 , 27.94401279, 17.83762764, 21.66941388, 18.93639614,
       20.01995795, 32.63414961, 17.86179976, 24.73211676, 26.77346826,
       27.26138023, 28.63243014, 21.16103038, 27.15098589, 23.33198614,
       21.02894005, 17.11819755, 37.52455938, 30.69864427,  8.46104486,
       20.83966032, 16.26732451, 25.05030307, 24.8069032 , 31.6789299 ,
       10.98989363, 13.54111562, 16.54697099, 35.86699683, 14.69589266,
       21.05655107, 13.90301353, 43.01321262, 17.80335305, 21.68817023,
       20.45077825, 17.38095983, 26.81334904, 10.08706217, 19.96174586,
       24.1983249 , 21.00202622, 29.38682967, 16.33215467, 19.37439646,
       14.45525235, 39.52670798, 18.18535021, 26.38536303, 20.41420863,
       25.08511581, 24.40208165, 24.87902769, 26.97887956,  4.93921657,
       24.0001365 , 10.66711602, 26.98494775, 16.63507993, 35.31652989,
       19.49249915, 27.37577863, 16.53965715, 19.09746715, 11.06765336,
       32.03445261, 36.15847648, 21.53547868, 24.96434626, 25.50

In [17]:
y_test

array([28.2, 23.9, 16.6, 22. , 20.8, 23. , 27.9, 14.5, 21.5, 22.6, 23.7,
       31.2, 19.3, 19.4, 19.4, 27.9, 13.9, 50. , 24.1, 14.6, 16.2, 15.6,
       23.8, 25. , 23.5,  8.3, 13.5, 17.5, 43.1, 11.5, 24.1, 18.5, 50. ,
       12.6, 19.8, 24.5, 14.9, 36.2, 11.9, 19.1, 22.6, 20.7, 30.1, 13.3,
       14.6,  8.4, 50. , 12.7, 25. , 18.6, 29.8, 22.2, 28.7, 23.8,  8.1,
       22.2,  6.3, 22.1, 17.5, 48.3, 16.7, 26.6,  8.5, 14.5, 23.7, 37.2,
       41.7, 16.5, 21.7, 22.7, 23. , 10.5, 21.9, 21. , 20.4, 21.8, 50. ,
       22. , 23.3, 37.3, 18. , 19.2, 34.9, 13.4, 22.9, 22.5, 13. , 24.6,
       18.3, 18.1, 23.9, 50. , 13.6, 22.9, 10.9, 18.9, 22.4, 22.9, 44.8,
       21.7, 10.2, 15.4, 25.3, 23.3,  7.2, 21.2, 11.7, 27. , 29.6, 26.5,
       43.5, 23.6, 11. , 33.4, 36. , 36.4, 19. , 20.2, 34.9, 50. , 19.3,
       14.9, 26.6, 19.9, 24.8, 21.2, 23.9, 20.6, 23.1, 28. , 20. , 23.1,
       25. ,  9.7, 23.9, 36.1, 13.4, 12.7, 39.8, 10.4, 20.6, 17.8, 19.5,
       23.7, 28.5, 24.3, 23.8, 19.1, 28.4, 20.5, 33

In [18]:
y_test-y_pred

array([-4.1914647 , -4.04401279, -1.23762764,  0.33058612,  1.86360386,
        2.98004205, -4.73414961, -3.36179976, -3.23211676, -4.17346826,
       -3.56138023,  2.56756986, -1.86103038, -7.75098589, -3.93198614,
        6.87105995, -3.21819755, 12.47544062, -6.59864427,  6.13895514,
       -4.63966032, -0.66732451, -1.25030307,  0.1930968 , -8.1789299 ,
       -2.68989363, -0.04111562,  0.95302901,  7.23300317, -3.19589266,
        3.04344893,  4.59698647,  6.98678738, -5.20335305, -1.88817023,
        4.04922175, -2.48095983,  9.38665096,  1.81293783, -0.86174586,
       -1.5983249 , -0.30202622,  0.71317033, -3.03215467, -4.77439646,
       -6.05525235, 10.47329202, -5.48535021, -1.38536303, -1.81420863,
        4.71488419, -2.20208165,  3.82097231, -3.17887956,  3.16078343,
       -1.8001365 , -4.36711602, -4.88494775,  0.86492007, 12.98347011,
       -2.79249915, -0.77577863, -8.03965715, -4.59746715, 12.63234664,
        5.16554739,  5.54152352, -5.03547868, -3.26434626, -2.80

In [19]:
((y_test - y_pred)**2).mean()

19.831323672063174

In [20]:
from sklearn.metrics import mean_squared_error

In [21]:
mean_squared_error(y_test, y_pred)

19.831323672063174

In [22]:
SST = ((y_test-y_test.mean())**2).sum()

In [23]:
SSE = ((y_test-y_pred)**2).sum()

In [24]:
1 - SSE/SST

0.7836295385076287

In [25]:
from sklearn.metrics import r2_score

In [26]:
r2_score(y_test, y_pred)

0.7836295385076287