<a href="https://colab.research.google.com/github/Long-Live-Lord-Voldemort/Long-Live-Lord-Voldemort/blob/main/Option_Pricing_MonteCarlo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
S = 100
T = 1
r = 0.07
sigma = 0.2
Nsimulations = 5000
Nsteps = 4
K = 100

In [ ]:
dt = T/Nsteps

In [ ]:
import numpy as np

drift = (r-(sigma**2)/2)*dt
a = sigma*np.sqrt(dt)
x = np.random.normal(0,1,(Nsimulations,Nsteps))
x

array([[ 0.68830974,  0.05325483,  1.03685519, -0.98994266],
       [-0.6349243 ,  0.68656739, -1.08872435, -0.00955234],
       [-0.07430282, -0.62962236, -0.80605956, -0.19938012],
       ...,
       [ 1.00055253, -0.57361893,  1.21114856, -1.19360369],
       [-1.8033876 , -0.80933248, -0.71131583, -0.33684296],
       [ 1.03361252,  0.62892543, -1.08178304,  0.29215169]])

In [ ]:
Smat = np.zeros((Nsimulations,Nsteps))
Smat[:,0]+=S

for i in range(1,Nsteps):
  Smat[:,i] += Smat[:,i-1] * np.exp(drift +a*x[:,i])
Smat

array([[100.        , 101.79853055, 114.34053992, 104.86637508],
       [100.        , 108.45408731,  98.48994777,  99.63357991],
       [100.        ,  95.07898335,  88.81912459,  88.16093773],
       ...,
       [100.        ,  95.61295208, 109.28106578,  98.20555472],
       [100.        ,  93.38557945,  88.06765754,  86.22162865],
       [100.        , 107.83073499,  97.9918611 , 102.16606667]])

In [ ]:
q = Smat[:,-1]-K
for i in range(len(q)):
  if q[i]<0:
    q[i]=0
  else:
      q[i]=q[i]
q

array([4.86637508, 0.        , 0.        , ..., 0.        , 0.        ,
       2.16606667])

In [ ]:

p = K-Smat[:,-1]
for i in range(len(p)):
  if p[i]<0:
    p[i]=0
  else:
      p[i]=p[i]
p

array([ 0.        ,  0.36642009, 11.83906227, ...,  1.79444528,
       13.77837135,  0.        ])

In [ ]:
payoff_call=np.mean(q)
payoff_put=np.mean(p)

In [ ]:
payoff_put

4.709927204567519

In [ ]:
payoff_call

10.43112071215092

In [ ]:
call = payoff_call*np.exp(-r*T)
put = payoff_put*np.exp(-r*T)

In [ ]:
call

9.725912486702452

In [ ]:
put

4.391507017745654